export const PERMISSIONS = {
  // User Management
  USER_CREATE: 'USER.CREATE',
  USER_UPDATE: 'USER.UPDATE',
  USER_VIEW: 'USER.VIEW',
  USER_DELETE: 'USER.DELETE',

  // Incident Management
  INCIDENT_CREATE: 'INCIDENT.CREATE',
  INCIDENT_UPDATE_OWN: 'INCIDENT.UPDATE_OWN',
  INCIDENT_UPDATE_ANY: 'INCIDENT.UPDATE_ANY',
  INCIDENT_VIEW_OWN: 'INCIDENT.VIEW_OWN',
  INCIDENT_VIEW_SITE: 'INCIDENT.VIEW_SITE',
  INCIDENT_APPROVE: 'INCIDENT.APPROVE',
  INCIDENT_CLOSE: 'INCIDENT.CLOSE',

  // Shift Management
  SHIFT_VIEW_OWN: 'SHIFT.VIEW_OWN',
  SHIFT_VIEW_TEAM: 'SHIFT.VIEW_TEAM',
  SHIFT_ASSIGN: 'SHIFT.ASSIGN',
  SHIFT_CHECKIN: 'SHIFT.CHECKIN',
  SHIFT_CHECKOUT: 'SHIFT.CHECKOUT',

  // Patrol Management
  PATROL_EXECUTE: 'PATROL.EXECUTE',
  PATROL_VIEW_TEAM: 'PATROL.VIEW_TEAM',
  PATROL_OVERRIDE: 'PATROL.OVERRIDE',

  // Reports
  REPORT_SUBMIT: 'REPORT.SUBMIT',
  REPORT_VIEW_OWN: 'REPORT.VIEW_OWN',
  REPORT_VIEW_TEAM: 'REPORT.VIEW_TEAM',
  REPORT_APPROVE: 'REPORT.APPROVE',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export const ROLES = {
  ADMIN: 'ADMIN',
  SUPERVISOR: 'SUPERVISOR',
  GUARD: 'GUARD',
} as const;

export type RoleName = typeof ROLES[keyof typeof ROLES];

export const ROLE_PERMISSIONS = {
  GUARD: [
    PERMISSIONS.INCIDENT_CREATE,
    PERMISSIONS.INCIDENT_UPDATE_OWN,
    PERMISSIONS.INCIDENT_VIEW_OWN,
    PERMISSIONS.SHIFT_VIEW_OWN,
    PERMISSIONS.SHIFT_CHECKIN,
    PERMISSIONS.SHIFT_CHECKOUT,
    PERMISSIONS.PATROL_EXECUTE,
    PERMISSIONS.REPORT_SUBMIT,
    PERMISSIONS.REPORT_VIEW_OWN,
  ],
  
  SUPERVISOR: [
    PERMISSIONS.INCIDENT_CREATE,
    PERMISSIONS.INCIDENT_UPDATE_ANY,
    PERMISSIONS.INCIDENT_VIEW_SITE,
    PERMISSIONS.INCIDENT_APPROVE,
    PERMISSIONS.INCIDENT_CLOSE,
    PERMISSIONS.SHIFT_VIEW_TEAM,
    PERMISSIONS.SHIFT_ASSIGN,
    PERMISSIONS.PATROL_VIEW_TEAM,
    PERMISSIONS.PATROL_OVERRIDE,
    PERMISSIONS.REPORT_VIEW_TEAM,
    PERMISSIONS.REPORT_APPROVE,
    PERMISSIONS.USER_VIEW,
  ],
  
  ADMIN: ['*'], // All permissions
} as const;